name: flutter_scan_bluetooth
description: Flutter plugin to scan Bluetooth devices.
version: 3.0.0
homepage: https://github.com/kiwi-bop/flutter_scan_bluetooth

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kiwi.flutterscanbluetooth
        pluginClass: FlutterScanBluetoothPlugin
      ios:
        pluginClass: FlutterScanBluetoothPlugin

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"
