name: flutter_scan_bluetooth
description: Flutter plugin to scan Bluetooth devices.
version: 3.0.0
homepage: https://github.com/kiwi-bop/flutter_scan_bluetooth

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.kiwi.flutterscanbluetooth
        pluginClass: FlutterScanBluetoothPlugin
      ios:
        pluginClass: FlutterScanBluetoothPlugin
